// src/front-end/ts/components/chart.component.ts
import {Component, Input} from '@angular/core';
import * as _ from "lodash";

@Component({
    selector: 'chart',
    template: `
    <div class="{{className}} container">
        <div class="row">
            <div *ngIf="!weather[0]" class="col-xs-12 text-center paddings">Loading... Please wait.</div>
            <div *ngIf="weather[0]" class="col-xs-12">
                <h2>{{name}}</h2>
                <div class="text-center">
                    <label>select city</label>
                    <select [(ngModel)]="selectedCity" (change)="updateChart()">
                        <option *ngFor="let city of cities" [ngValue]="city.value">
                            {{city.name}}
                        </option>
                    </select>
                    <label>select params</label>
                    <select [(ngModel)]="selectedParam" (change)="updateChart()">
                        <option *ngFor="let param of params" [ngValue]="param.value">
                            {{param.name}}
                        </option>
                    </select>
                </div>
                <canvas baseChart
                [chartType]="type"
                [datasets]="chartData"
                [options]="chartOptions"
                [labels]="chartLabels"
                [colors]="chartColors"
                [legend]="chartLegend"></canvas>
            </div>
        </div>
    </div>`,
    styles: [
        'canvas{ max-width: 800px; margin: 15px auto; height:auto; max-height: 380px;}',
        '.paddings{padding: 15px; font-size:25px;}'
    ]
})

export class ChartComponent {
    public name: string;
    public className: string;
    public chartData: Array<any>;
    public chartOptions: any;
    public chartColors: Array<any>;
    public chartLegend: boolean;
    public params: Array<any>;
    public selectedParam: string;
    public cities: Array<any>;
    public chartLabels = [''];
    public selectedCity: string;
    @Input() weather: any;
    @Input() type: string;

    constructor() {
        this.name = "Current Weather Chart";
        this.className = "current-chart";
        this.chartData = [
            {data: [0], label: 'Service A'},
            {data: [0], label: 'Service B'},
            {data: [0], label: 'Service C'}
        ];
        this.chartOptions = this.getChartOptions();
        this.chartColors = this.getChartColors();
        this.chartLegend = true;
        this.cities = [
            {id: 1, name: "Rivne", value:"Rivne"},
            {id: 2, name: "Kiev", value:"Kiev"},
            {id: 3, name: "Luts'k", value:"Luts'k"}
        ];
        this.params = [
            {id: 1, name: "Temperature", value: "temp"},
            {id: 2, name: "Humidity", value: "humidity"},
            {id: 3, name: "Pressure", value: "pressure"},
            {id: 4, name: "Wind speed", value: "windSpeed"}
        ];
        this.selectedParam = _.first(this.params).value;
        this.selectedCity = _.first(this.cities).value;
    };

    ngOnChanges() {
        let data = this.weather;
        if (data.destination) {
            return false;
        }
        this.updateChart();
    };

    public updateChart(){
        this.chartData = this.getChartData();
        this.chartOptions = this.getChartOptions();
    };

    private getChartData() {
        let weather = this.weather,
            result = [],
            city = this.selectedCity,
            param = this.selectedParam;

        _.each(weather, function(item){
            if (item.cityName === city){
                let data = parseFloat(item[param]);
                result.push({
                    data: [data],
                    label: item.sourceAPI
                })
            }
        });
        return result;
    };

    private getChartOptions() {
        return {
            responsive: true,
            scales: {
                yAxes: [{
                    ticks: this.getChartTicks()
                }]
            }
        };
    };

    private getChartTicks(){
        let result = {
            suggestedMin: 0,
            suggestedMax: 0,
            beginAtZero: true
        };
        switch (this.selectedParam){
            case "temp":
                result.suggestedMax = 30;
                return result;
            case "humidity":
                result.suggestedMin = 50;
                result.suggestedMax = 100;
                result.beginAtZero = false;
                return result;
            case "pressure":
                result.suggestedMin = 700;
                result.suggestedMax = 1200;
                result.beginAtZero = false;
                return result;
            case "windSpeed":
                result.suggestedMin = 10;
                result.suggestedMax = 30;
                result.beginAtZero = false;
                return result;
        }
        return result;
    };

    private getChartColors() {
        return [
            { // pink
                backgroundColor: '#ffbac7',
                borderColor: '#ff1744',
                pointBackgroundColor: '#ff1744',
                pointBorderColor: '#fff',
                pointHoverBackgroundColor: '#fff',
                pointHoverBorderColor: '#ff1744'
            },
            { // green
                backgroundColor: '#e1f0d1',
                borderColor: '#9ccc65',
                pointBackgroundColor: '#9ccc65',
                pointBorderColor: '#fff',
                pointHoverBackgroundColor: '#fff',
                pointHoverBorderColor: '#9ccc65'
            },
            { // blue
                backgroundColor: '#bde0fb',
                borderColor: '#2196f3',
                pointBackgroundColor: '#2196f3',
                pointBorderColor: '#fff',
                pointHoverBackgroundColor: '#fff',
                pointHoverBorderColor: '#2196f3'
            }
        ];
    };

}

// src/front-end/js/components/chart.jsx
import React from "react";
import {Bar} from "react-chartjs-2";
import {CHART_TYPES, CHART_PARAMS} from "./../constants/constants.jsx";
import {changeChartCityAction, changeChartParamAction} from "./../actions/currentWeatherChartActions.jsx";
import _ from "lodash";


export default class Chart extends React.Component {
    constructor(props){
        super(props);
        this._getChartLabel = this._getChartLabel.bind(this);
        this._getServicesByCity = this._getServicesByCity.bind(this);
        this.handleCity = this.handleCity.bind(this);
        this.handleParam = this.handleParam.bind(this);
        this._getOptionsByParam = this._getOptionsByParam.bind(this);
        this._getMaximalValue = this._getMaximalValue.bind(this);
    }

    componentWillMount(){
        this.setState({
            options: this._getOptionsByParam(this.props.currentChart.chartParam)
        });
    }

    handleCity(event){
        changeChartCityAction(event.target.value);
        // this.setState({city: event.target.value});
    }

    handleParam(event){
        let options = this._getOptionsByParam(event.target.value);
        changeChartParamAction(event.target.value);
        this.setState({
            options
        });
    }

    _getOptionsByParam(param){
        const options = {
            responsive: true,
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }],
                xAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        };
        return options
    }

    _getServicesByCity(){
        let services = [];
        let data = [];
        let city = this.props.currentChart.chartCity;
        let label = this.props.currentChart.chartParam;
        _.each(this.props.weather, (item) => {
            if (item.cityName === city){
                services.push(item.sourceAPI);
                data.push(item[label]);
            }
        });
        return {services, data};
    }
    //TODO this should be taken from config
    _getMaximalValue(param){
        switch (param) {
            case CHART_PARAMS.PREASURE.LABEL:
                return CHART_PARAMS.PREASURE.MAX;
            case CHART_PARAMS.HUMIDITY.LABEL:
                return CHART_PARAMS.HUMIDITY.MAX;
            case CHART_PARAMS.WIND_SPEED.LABEL:
                return CHART_PARAMS.WIND_SPEED.MAX;
            case CHART_PARAMS.TEMPERATURE.LABEL:
                return CHART_PARAMS.TEMPERATURE.MAX;
        }
    }
    //TODO this should be taken from config
    _getChartLabel(){
        switch (this.props.currentChart.chartParam) {
            case CHART_PARAMS.PREASURE.LABEL:
                return CHART_PARAMS.PREASURE.NAME;
            case CHART_PARAMS.HUMIDITY.LABEL:
                return CHART_PARAMS.HUMIDITY.NAME;
            case CHART_PARAMS.WIND_SPEED.LABEL:
                return CHART_PARAMS.WIND_SPEED.NAME;
            case CHART_PARAMS.TEMPERATURE.LABEL:
                return CHART_PARAMS.TEMPERATURE.NAME;
        }
    }

    render() {
        let weather = this._getServicesByCity();
        const data = {
            labels: weather.services,
            datasets: [
                {
                    label: this._getChartLabel(),
                    backgroundColor: [
                        "rgba(255, 99,  132, 0.2)",
                        "rgba( 54, 162, 235, 0.2)",
                        "rgba(255, 206,  86, 0.2)"
                    ],
                    borderColor: [
                        "rgba(255, 99,  132, 1)",
                        "rgba( 54, 162, 235, 1)",
                        "rgba(255, 206,  86, 1)"

                    ],
                    borderWidth: 1,
                    data: weather.data
                }
            ]
        };

        return (
            <section className="current-weather">
                <div className="container">
                    <div className="row">
                        <div className="col-xs-12 col-sm-4">
                            <h2>Current Weather Chart</h2>
                        </div>
                        <div className="col-xs-12 col-sm-4">
                            <label>City:</label>
                            <select
                                onChange={this.handleCity}
                                value={this.props.currentChart.chartCity}
                            >
                                <option value="Rivne">Rivne</option>
                                <option value="Kiev">Kiev</option>
                                <option value="Luts'k">Luts'k</option>
                            </select>
                        </div>
                        <div className="col-xs-12 col-sm-4">
                            <label>Parameter:</label>
                            <select
                                onChange={this.handleParam}
                                value={this.props.currentChart.chartParam}
                            >
                                <option value="temp">Temperature</option>
                                <option value="pressure">Pressure</option>
                                <option value="humidity">Humidity</option>
                                <option value="windSpeed">Wind Speed</option>
                            </select>
                        </div>
                    </div>
                </div>
                <Bar
                    data={data}
                    options={this.state.options}
                />
            </section>
        );
    }
}
Chart.propTypes = {
    currentChart: React.PropTypes.object,
    weather: React.PropTypes.array
}
